/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\resources\stl\cansatCompressed.gltf --transform
*/
import { useGLTF } from "@react-three/drei";
import React, { useRef } from 'react'

export function Cansat(props) {
  const ref = useRef();
  const { nodes, materials } = useGLTF("/cansat.gltf");
  materials.default.wireframe = false;
  return (
    <group {...props} ref={ref} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={materials.default} />
    </group>
  );
}
useGLTF.preload("/cansat.gltf");
